### ISSUE TITLE
issue with query with some criteria

### ISSUE THREAD

**Issue by Tunis** [OnyxDevTools/onyx-database-parent#97] opened 2018-06-17 17:33 UTC
Hello,

i found your project and tried it to see how it work, well i can say it is fairly simple to use and really that change of the big distrib :)

i have use it in a test project, it work well and all, but i have one issue that i don't know if it is me that don't use the system correctly or if it's a bug :/
the Item Object contain a list of Tag, i want to filter items base on this list.

> this is the query :
```java
final QueryCriteria byName = new QueryCriteria("name", QueryCriteriaOperator.CONTAINS, name);
final QueryCriteria byTag = prepareTagCriteria(includeTags, excludeTags);
if(byTag != null) {
            byName.and(byTag);
}
final Query query = new Query(Item.class, byName);
return manager.executeQuery(query);
```
> the prepareTagCriteria method : 
```java
    if(tags != null || excludeTags != null) {
            final QueryCriteria[] byTag = new QueryCriteria[1];
            if(tags != null) {
                tags.forEach(t -> {
                    if (byTag[0] == null) {
                        byTag[0] = new QueryCriteria("tags.name", QueryCriteriaOperator.EQUAL, t.getName());
                    } else {
                        byTag[0].and(new QueryCriteria("tags.name", QueryCriteriaOperator.EQUAL, t.getName()));
                    }
                });
            }
            if(excludeTags != null) {
                excludeTags.forEach(t -> {
                    System.out.println("EXCLUDE TAG : " + t.getName());
                    if (byTag[0] == null) {
                        byTag[0] = new QueryCriteria("tags.name", QueryCriteriaOperator.NOT_EQUAL, t.getName());
                    } else {
                        byTag[0].and(new QueryCriteria("tags.name", QueryCriteriaOperator.NOT_EQUAL, t.getName()));
                    }
                });
            }
            return byTag[0];
        }
        return null;
```

I use a ListView to populate the excludeTag and selectedTag list (work well, the tag are add the the selectedTag or excludeTag base on click).
The request work fine for all the case but the excludeTag case.

For example if i selected tag action the request will return 4 items, and if i add horror it became 3 items (i want only item that containt the 2 tag) that work well. (i can event add tags and name filter it's ok)

But if i say i want action tag but not the horror tag i hope to see only 1 item, or i just see all 4 items, it seem like the excludeTag is ignored.

I have another odd thing happening.
I have 700 item in bdd, i select a tag that return 100 items if i exclude this tag it return 300 items (already a bad result...), and for each exclude tag i add, it always return 300 items ( like the other tag where not add to the request, but the query have all the criteria, checked with getAllCriteria on the query, each new tag add a criteria, and i see each time the tag passed in the foreach ).
Another thing to note, if i juste manually add a exclude tag criteria, let say "truc" that don't exist in bdd, i still get 300 result...

I did try to use the .not() didn't change anything.
I did try the other criteria option (LIKE, CONTAIN, MATCH, etc...)
So is it me that don't understand the use of the criteria or it is a bug?
The result i would hope to see was to remove all items that have the exclude tag in them.

Well i hope someone can show me the light on that one, i really like the simplicity of this solution for small project.

Good day to you.

Ps : sorry if i made mistake in my text, i'm not native english :p

**Comment by timbob1000** [comment] 2018-06-22 20:38
Can you also post your entity classes?  I'd like to know if the 'tags.name' is indexed or partitioned.

Also, by design Onyx does not support querying relationships as the first Query Criteria.  The reason, is that it is not efficient.  Behind the scenes, it has the reference the relationship structure for all items within a full table scan.  For large data sets, that could cause a bottleneck.  If that is the case, rather than querying the parent entity, I recommend querying the Tags entity directly.

Irrespective, if you attach the entity objects, I will attempt to reproduce.

**Comment by Tunis** [comment] 2018-06-22 21:01
Hello,

thank for the response,
just for the test i did a really simple tag entity with only name field :p

tag entity : 
```java
    @Identifier
    @Attribute
    private String name;
```

item entity :
```java
    @Identifier
    @Attribute
    private long id;
    @Index
    @Attribute
    private String name;
    @Attribute
    private Date date;
    @Index
    @Attribute
    private Category category;
    @Index
    @Relationship(type = RelationshipType.ONE_TO_MANY,
            inverseClass = Tag.class,
            inverse = "tag",
            cascadePolicy = CascadePolicy.ALL,
            fetchPolicy = FetchPolicy.LAZY)
    private List<Tag> tags;
```

the complete query building :
```java
        name = name == null ? "": name;
        final QueryCriteria byName = new QueryCriteria("name", QueryCriteriaOperator.CONTAINS, name);
        final QueryCriteria byTag = prepareTagCriteria(includeTags, excludeTags);
        final QueryCriteria byCategories = prepareCategoriesCriteria(categories);

        if(byTag != null) {
            byName.and(byTag);
        }
        if(byCategories != null) {
            byName.and(byCategories);
        }
        final List<QueryOrder> queryOrders = Arrays.asList(new QueryOrder("name", true), new QueryOrder("date", true));
        final Query query = new Query(Item.class, byName);
        query.setQueryOrders(queryOrders);
        return manager.executeQuery(query);
```
the methodes prepare"X"Criteria are almost all the same just to iterate thought the list and create criteria for each elements.

what do you mean by first criteria? i always add the item.name criteria and add the other after it or do i need to declare them with another syntax?

the query work well with includeTags ( with only 1 or many Tag ), it just don't work with the excludeTags( 1 or many alike ) but i don't see a reason that one work but not the other :/

Good Day :)

**Comment by timbob1000** [comment] 2018-06-22 22:15
By first criteria I mean if you were to write the following Query:

```
final QueryCriteria byTag = QueryCriteria("tags.name", QueryCriteriaOperator.EQUAL, "someValue");
final Query query = new Query(byTag);
manager.executeQuery(query);
```

In that case, it would attempt to do a full table scan on a relationship predicate tags.name for the first sweep.  That is not supported.

That does not appear to be the case in your example.

At first glance, I see the following issue:

```
  @Index
  @Relationship(type = RelationshipType.ONE_TO_MANY,
            inverseClass = Tag.class,
            inverse = "tag",
            cascadePolicy = CascadePolicy.ALL,
            fetchPolicy = FetchPolicy.LAZY)
    private List<Tag> tags;
```

The @Index annotation is not supported here.  The index annotation is only for properties and not relationships.  By default all relationships should be indexed therefore there is no need for it regardless.

I've created a unit test and was unable to reproduce even after removing the Index annotation.

What version are you using?  There were known issues querying relationships in earlier versions.

Can you attach a working sample that reproduces the issue?

Sorry for the inconvenience and thank you for your continued support.

**Comment by Tunis** [comment] 2018-06-22 23:47
hope it will help you :
https://github.com/Tunis/testOnyx2

i use the lastest maven version (2.1.3), java 1.8_162

i've clean the code, remove @Index on relationships and try it again but still the issue

Good night :)

**Comment by timbob1000** [comment] 2018-06-27 19:55
So, I think I know what the issue may be.  The Query Criteria that match a One to Many relationship will return a result in which any of the items in the relationship has a match.  So for instance, in your example if I were to write a query:

`
List<Item> results = dao.filterItems(Arrays.asList(tag1), Arrays.asList(tag1), null, null, null, "item");
`

Since, 'Item 1' has a tags with names 'test 1' and 'test 3' it matches the criteria of having a Tag 'test 1' and having a tag with name not equal 'test 1 i.e 'test 3''.

If you were to use a standard SQL database such as Oracle, I believe the functionality you are looking for is the 'minus' operator.  For the time being, this is not a function within Onyx.  If this is the case, I would recommend executing 2 queries and aggregating the lists.  

If you are open to using Kotlin, you could use the List minus operator and function and use the following syntax:

```
val results = manager.from(Item::class)
                                    .where("name" cont "item")
                                    .and("tags.name" IN includeTags.map { it.name })
                                    .list<Item>() 
                                    .minus(manager.from(Item::class)  // or - operator
                                                               .where("name" cont "item")
                                                               .and("tags.name" notIn excludeTags.map { it.name })
                                                               .list<Item>())
```
Another thing I noticed is that in the code example you have: 

```
    private QueryCriteria prepareTagCriteria(QueryCriteria criteria, List<Tag> tags, List<Tag> excludeTags) {
        if (tags != null || excludeTags != null) {
            final QueryCriteria[] byTag = new QueryCriteria[2];
            if (tags != null) {
                tags.forEach(t -> {
                    if (byTag[0] == null) {
                        byTag[0] = new QueryCriteria("tags.name", QueryCriteriaOperator.EQUAL, t.getName());
                    } else {
                        byTag[0].and(new QueryCriteria("tags.name", QueryCriteriaOperator.EQUAL, t.getName()));
                    }
                });
                criteria.and(byTag[0]);
            } 

```

The `byTag[0].and(new QueryCriteria("tags.name", QueryCriteriaOperator.EQUAL, t.getName()));` may need to be replaced with an 'or' to get your desired results.  Or you can use the IN QueryCriteriaOperator if you send in a list of tag Ids.  

Let me know if this is the case.

Best Regards,

Tim

**Comment by Tunis** [comment] 2018-06-27 21:45
oh yeah you are right :s

```sql
SELECT i.*
FROM items i
WHERE i.id NOT IN
      ( SELECT z.id_item
        FROM liai_item_tag z
        WHERE z.id_item IS NOT NULL
              AND z.id_tag = 'tag 3'
      )
  AND i.id IN (
  SELECT y.id_item
    FROM liai_item_tag y
  WHERE y.id_item IS NOT NULL
  AND y.id_tag = 'tag 1'
)
```

that's a mysql query for the result that i want, i'm not sure why i didn't just try to reproduce it. ^^

so how does the IN and NOT IN criteria work? do i pass them a query item or just the list of my tags that i want in or not in?

i did see that the kotlin version offer more flexibility for the query but i have never use kotlin. ^^ Maybe i will try it but since i don't work in java anymore it's only in my free time x) 

well thanks for your time and help :)

good night :)

**Comment by timbob1000** [comment] 2018-06-28 16:23
The IN and NOT_IN criteria requires a List of identifiers.  In the code example I put above, the `includeTags.map { it.name }` just maps the List of tags to a list of tag names.  It works very much like a SQL databases' IN operator.  I have thought about supporting overloading the IN operator to support a list of objects such as Tags in this case but, hydrating entire objects to use within an IN clause for large data sets would seem wasteful.  

If the field is indexed while using the IN criteria operator, it will match indexed results thus reducing the cost of the Query.

Happy to help.  I will close this ticket.  If you have any other questions, hit me up via email.

Best Regards, 

Tim

**Closed by timbob1000** 2018-06-28 16:23 UTC
